version: "3.9"
services:

  api_easy_broker:
    volumes:
      - ./api/app:/code/app
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./api/.env
    ports:
      - 8000:8000

  app_easy_broker:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    depends_on:
      - api_easy_broker
